services:
  client:
    build: ./client
    command: npm start
    ports:
      - 3020:3020
    depends_on:
      - server
    volumes:
      - ./client:/opt/client
      - client_node_modules:/opt/client/node_modules

  serverdb:
    image: mongo
    restart: always
    ports:
      - 27075:27017
    volumes:
      - serverdata:/var/lib/server/data

  server:
    build: ./server
    command: python main.py
    ports:
      - 8010:8010
    depends_on:
      - serverdb
    volumes:
      - ./server:/opt/server

volumes:
  client_node_modules:
  serverdata: